### ISSUE TITLE
Outdated technique for touch screen and hover events 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-dropdown#37]
This technique is outdated and no longer needed as `@media (hover)` is [supported by all browsers](https://caniuse.com/mdn-css_at-rules_media_hover)

https://github.com/AlaskaAirlines/auro-dropdown/blob/5a872847403854bdd065a3f3d224957fad47b1ca/src/auro-dropdown.js#L30-L34

See example from [auro-button](https://github.com/AlaskaAirlines/auro-button/blob/master/src/style.scss#L120-L126)

```css
  @media (hover: hover) {
    &:active,
    &:hover {
      background-color: var(--auro-color-ui-hover-on-light);
      border: 1px solid var(--auro-color-ui-hover-on-light);
    }
  }
```

Reviewing the Sass file, I see that we are not handling this scenario and hover events will be triggered on mobile devices.
